[package]
name = "queensway"
version = "0.1.0"
edition = "2021"

[dependencies]
phf = { version = "0.10", features = ["macros"] }
rayon = "1.5"
regex = "1"
tokio = { version = "1.18.2", features = ["full"] }